@startuml
!pragma layout smetana
'https://plantuml.com/class-diagram

hide circle
hide method

class Order {
    item number
    width
    length
    name
    price
    description

}

class Material {
    height
    width
    length
    price
    description
}
class Customer {
    name
    address
    telephone number
}

class SalesPerson {

}

class PartsList {
name
length
width
height
unit
quantity
functional description


}

class Fog {
}

Fog -right- "*" SalesPerson: has >
Order "*" -right- "*" Material: consists of >
Fog -right- "*" Order: administrates >
SalesPerson "1"-right- "*"Customer: serves  >
Customer "1" -- "*" Order: places  >
Order "1" -- "1" PartsList: consists of >
PartsList "1" -right- "*" Material: consists of >



@enduml