@startuml

Title Navigation Diagram

[*] --> Index: Open homepage
payment --> purchasereceipt: payment successful
payment --> payment: payment unsuccessful
purchasereceipt -> [*]


Index -right-> custompage: choose custom
custompage -right-> createuser: no account
custompage --> login: already have an account

createuser --> createuser: unsuccessful, try again
createuser -right-> login: account created
login -right-> offeroverview: Login successful
login --> login: unsuccessful, try again
login -left-> createuser: no account
offeroverview --> payment: Offer accepted

offeroverview --> requestreceipt: request send
requestreceipt --> [*]


Index --> login: already have an account

state admin {
login --> adminrequest: successful admin login
adminrequest -right-> material: material update
adminrequest --> offercalculator: choose a request
material --> editmaterial: edit material
editmaterial --> material: succes
editmaterial--> editmaterial: error, try again
material --> [*]: no more edits
material --> material: material deleted
offercalculator --> adminrequest: offer send to customer
adminrequest --> [*]
}

@enduml