@startuml

Title state_diagram

[*] --> Index: Open homepage
Index -left-> Premade_Carport: choose premade
Premade_Carport --> Payment: choose to purchase
Payment --> Invoice: Payment successful
Payment --> Payment: Payment unsuccessful
Invoice -> [*]


Index -right-> Custom_Carport: choose custom
Custom_Carport --> Create_account: no account
Custom_Carport --> Log_in: already have an account

Create_account --> Create_account: unsuccessful, try again
Create_account --> Log_in: account created
Log_in --> Overview: Login successful
Log_in --> Log_in: unsuccessful, try again
Log_in --> Create_account: no account
Overview --> Offer: received offer
Offer -> Payment: Offer accepted
Overview --> receipt: request send
receipt --> [*]


Index --> Log_in: already have an account

state admin {
Log_in --> Request_List: successful admin login
Request_List -right-> Material: material update
Request_List --> Offer_Calculator: choose a request
Material --> Edit_Material: edit material
Edit_Material --> Material: succes
Edit_Material--> Edit_Material: error, try again
Material --> [*]: no more updates
Material --> Material: material deleted
Offer_Calculator --> Request_List: offer send to customer
Request_List --> [*]
}

@enduml